server {
    listen 443 ssl;
    server_name sso.smileyfam.me;
    access_log off;

    location / {
        grpc_pass grpc://zitadel;
        grpc_set_header Host $host;
    }
}

server {
    listen 443 ssl;
    server_name auth.smileyfam.me;
    access_log off;

    location / {
        include /etc/nginx/conf.d/proxy.conf;
        proxy_pass http://authentik;
        proxy_set_header Connection $connection_upgrade;
    }
}

server {
    listen 443 ssl;
    server_name metube.${HOSTNAME};
    access_log off;

    location / {
        include /etc/nginx/conf.d/proxy.conf;
        proxy_pass http://metube;
    }
}

server {
    listen 443 ssl;
    server_name pgadmin.${HOSTNAME};
    access_log off;
    
    location / {
        proxy_pass http://pgadmin;
        proxy_set_header Host $host;
        proxy_redirect off;
    }
}

server {
    listen 443 ssl;
    server_name gallery.${HOSTNAME};
    access_log off;

    location / {
        include /etc/nginx/conf.d/proxy.conf;
        proxy_pass http://gallery;
    }
}