networks:
  common:
    name: common

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    networks:
      - common
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER_VOL}/portainer:/data
    ports:
      - 9000:9000

  moon-v2:
    build:
      context: ../../moonV2
      dockerfile: Dockerfile
    container_name: moon-v2
    networks:
      - common
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: 0.05
          memory: 30M

  syncthing:
    image: syncthing/syncthing:2
    container_name: syncthing
    networks:
      - common
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ${DOCKER_VOL}/syncthing/config:/var/syncthing/config
      - /mnt/data:/var/syncthing/Sync
    ports:
      - 127.0.0.1:8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    restart: unless-stopped
