services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    networks:
      - common
    user: 1000:1000 # should be owner of volumes
    ports:
      - 127.0.0.1:4533:4533
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 0
      ND_LOGLEVEL: info
      ND_SESSIONTIMEOUT: 168h # a week
      ND_BASEURL: ""
      ND_CONFIGFILE: /data/navidrome.toml
      ND_BACKUP_PATH: /backup
      ND_BACKUP_SCHEDULE: "0 2 * * *"
      ND_BACKUP_COUNT: 7
    volumes:
      - "${DOCKER_VOL}/navidrome:/data"
      - "${SYNC_PATH}/Music:/music:ro"
      - "${SYNC_PATH}/Backup/navidrome:/backup"