services:
  nginx-internal:
    image: nginx:1.27
    container_name: nginx-internal
    network_mode: host
    restart: unless-stopped
    command: sh -c 'mkdir -p /etc/nginx/sites && exec /docker-entrypoint.sh nginx -g "daemon off;"'
    env_file:
      - ${DOCKER_ENV}/nginx/.env
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/sites
    volumes:
      - ${HOME}/homelab/nginx/nginx-int.conf:/etc/nginx/nginx.conf:ro
      - ${HOME}/homelab/nginx/templates:/etc/nginx/templates:ro
      - ${HOME}/homelab/nginx/conf.d:/etc/nginx/conf.d:ro
      - ${HOME}/keystore:/etc/keystore:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro
      - ${SYNC_PATH}/Idols:/var/www/idols:ro
  
  nginx:
    build:
      context: ../dockerfiles
      dockerfile: nginx
    container_name: nginx-external
    hostname: nginx-external
    network_mode: host
    restart: unless-stopped
    command: sh -c 'mkdir -p /etc/nginx/sites && exec /docker-entrypoint.sh nginx -g "daemon off;"'
    env_file:
      - ${DOCKER_ENV}/nginx/.env
    environment:
      - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/sites
    volumes:
      - ${HOME}/homelab/nginx/nginx-ext.conf:/etc/nginx/nginx.conf:ro
      - ${HOME}/homelab/nginx/templates:/etc/nginx/templates:ro
      - ${HOME}/homelab/nginx/conf.d:/etc/nginx/conf.d:ro
      - /etc/letsencrypt/live:/etc/letsencrypt/live:ro
      - /etc/letsencrypt/archive:/etc/letsencrypt/archive:ro