name: immich

volumes:
  immich-redis:
    name: immich-redis
  immich-model-cache:
    name: immich-model-cache

networks:
  immich_network:
    name: immich

services:
  immich-server:
    image: ghcr.io/immich-app/immich-server:v2
    container_name: immich-server
    # extends: # uncomment this section for hardware acceleration - see https://immich.app/docs/features/hardware-transcoding
    #   file: hwaccel.transcoding.yml 
    #   service: cpu # set to one of [nvenc, quicksync, rkmpp, vaapi, vaapi-wsl] for accelerated transcoding
    networks:
      - immich_network
    volumes:
      - /mnt/data/docker-volume/immich:/usr/src/app/upload
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - ${DOCKER_ENV}/immich/.env
    depends_on:
      - redis
      - database
    restart: unless-stopped
    ports:
      - 127.0.0.1:2283:2283
    healthcheck:
      disable: false

  immich-machine-learning:
    image: ghcr.io/immich-app/immich-machine-learning:v2
    container_name: immich-machine-learning
    networks:
      - immich_network
    volumes:
      - immich-model-cache:/cache
    env_file:
      - ${DOCKER_ENV}/immich/.env
    restart: unless-stopped
    healthcheck:
      disable: false

  redis:
    image: docker.io/valkey/valkey:8-bookworm@sha256:ff21bc0f8194dc9c105b769aeabf9585fea6a8ed649c0781caeac5cb3c247884
    container_name: immich-redis
    healthcheck:
      test: redis-cli ping || exit 1
    networks:
      - immich_network
    volumes:
      - immich-redis:/data
    restart: unless-stopped

  database:
    image: ghcr.io/immich-app/postgres:14-vectorchord0.3.0-pgvectors0.2.0
    container_name: immich-postgres
    networks:
      - immich_network
      - pgadmin
    env_file:
      - ${DOCKER_ENV}/immich/.env.database
    environment:
      POSTGRES_INITDB_ARGS: '--data-checksums'
    volumes:
      - ${DOCKER_VOL}/immich/postgres:/var/lib/postgresql/data
    restart: unless-stopped
